### ISSUE TITLE
Запуск симулятора

### ISSUE THREAD

**Issue by denisptuhov** [OSLL/drone_swarm_model#19]
В случае удачной "примитивной" проверки отправить данные в симулятор

**Comment by Astana-Mirza** [comment]
Задача выполнена. Создан класс Simulator, запускающий любую симуляцию (из папки simulation) фоновым процессом. Чтобы привязать его к получению решения, необходимо из xqueue-watcher'а запускать контейнер по приходу этого решения, и в контейнере вызывать скрипт.

Нужна задача на запуск контейнера в xqueue-watcher'e
